### PR TITLE
docs(example-app): Example app UI #202

### LINKED ISSUE #202: [feat] Bootstrap example application UI
**Does your feature request relate to a specific USWDS feature?**
No

**Is your feature request related to a problem? Please describe.**
This feature will demonstrate real-life usage of ReactUSWDS components and provide another avenue for testing.

**Describe the solution you'd like**
Add the following to the `/example` application:
- router
- basic navigation & page UI

**Additional context**
Initial discussion: https://github.com/trussworks/react-uswds/issues/77

### PR DESCRIPTION
**Pull request by suzubara**
# Summary

Bootstraps basic UI for the example application, including routing with [React Router](https://reacttraining.com/react-router/web/guides/quick-start).

## Related Issues or PRs

Closes #202 

## How To Test

Navigate to the `/example` directory, install dependencies (`yarn install`), and start the app (`yarn start`). Verify you can view the app, which currently just has two pages that are mostly empty (home & examples).

### Screenshots (optional)

image

### CODE REVIEW

**Comment by suzubara** [comment]
note: I ended up using react-router instead of hookrouter because I ran into some basic bugs with hookrouter and decided it would be better to use a more common library. I still don't love react-router but it feels like the lesser evil.

**Comment by trussworks-infra** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This PR does not include changes to storybook, even though it affects component code.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>This PR does not include changes to tests, even though it affects source code.</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 73f7ead4daa6ddc0f8a3d6236f3bd07a1d338e61
</p>

**Comment by haworku** [comment]
Suggestion: edit dangerfile to ignore changes in `/example`  for storybook and tests warnings.

**Comment by haworku** [comment]
Another option: could we have a script to run example app that does yarn build and then starts up app from `example` folder?

**Pull request merged**
