### PR TITLE
fix: add ActionType.CLEAR_FOCUS to indicate a user has left the field

### LINKED ISSUE #901: [fix] ComboBox forces focus when another field is changed
**ReactUSWDS Version & USWDS Version:**

ReactUSWDS `v1.10.0`
USWDS: `v2.8.1`

**Describe the bug**

My form has multiple fields. If I select an option from the `ComboBox`, then type in the input field, the `ComboBox` steals focus and I'm unable to finish filling out my text input.

https://user-images.githubusercontent.com/8367504/108134906-e9210900-706b-11eb-88d1-70b28b51d823.mov

**To Reproduce**
I was able to reproduce this error in Storybook.
```
export const comboBoxBug = (): React.ReactElement => {
  const [ val, setVal ] = useState('');
  const fruitList = Object.entries(fruits).map(([key, value]) => ({
    value: key,
    label: value,
  }))

  return (
    <Form onSubmit={noop}>
      <Label htmlFor="input-ComboBox">Combo Box</Label>
      <ComboBox
        id="input-ComboBox"
        name="input-ComboBox"
        options={fruitList}
        onChange={noop}
      />
      <Label htmlFor="test">Input Field</Label>
      <TextInput
        id="test"
        name="test"
        type="text"
        onChange={(e) => {
          setVal(e.target.value)
        }}
        value={val}
      />
    </Form>
  )
}
```
1. Select an option in the `ComboBox`
2. Type into the `TextInput`
BUG: Notice the focus switch to the `ComboBox` and disrupts the user's ability to type in the `TextInput`

**Expected behavior**
I expect the focus to remain unchanged.

### PR DESCRIPTION
**Pull request by christopherhuii**
# Summary
The ComboBox has issues with "losing" its focus when clicking outside of the component.

https://user-images.githubusercontent.com/8367504/108426115-35955180-71f0-11eb-91c1-9ea40d8bd920.mov

A related issue is that the `FocusMode` is still set to `FocusMode.Input` even after the user has left the component.

This PR allows the user to:
1. Unfocus from the ComboBox when they click outside
2. Resets the `FocusMode` to `None` when they click outside

I achieved this by creating a new `ActionType` called `CLEAR_FOCUS` to indicate when a user has clicked outside of the combo box. I am open to suggestions on the name. This action is different from `ActionType.CLEAR` because `CLEAR` empties the input, whereas `CLEAR_FOCUS` indicates the user has left the field.

## Related Issues or PRs
Fixes #901 

## How To Test
1. Open Storybook
2. Focus ComboBox by opening its options or typing in the input
3. Click outside of the component and the input should lose focus.

### Screenshots (optional)

After Fix:

https://user-images.githubusercontent.com/8367504/108428519-89556a00-71f3-11eb-8029-d19cf7703133.mov

### CODE REVIEW

**Comment by trussworks-infra** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This PR does not include changes to storybook, even though it affects component code.</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8f9408f88f6cac3377c42eacdcc0f69430cbde21
</p>

**Comment by christopherhuii** [comment]
Maybe `ActionType.BLUR` is a better name?

**Review by suzubara — DISMISSED** [review]
The changes & testing the component in Storybook look good to me! If they have time, I might look for a review from @haworku or @jim since they worked on the original component, but I feel pretty confident that this is an improvement.

> Maybe `ActionType.BLUR` is a better name?

I agree!

**Review by jim — APPROVED** [review]
This looks good to me! Thanks for digging into this component and fixing this issue.

**Pull request merged**
