### PR TITLE
Install loki #40

### PR DESCRIPTION
**Pull request by eamahanna**
## PR Description
This PR adds loki to preform visual regression testing for storybook. This tool looks at the rendered stories within storybook, creates *.png files of the stories, and compares them to the reference *.png files. This tool will add an additional testing step for developers. When a story's visual representation is changed, or potentially changed, the developer will need to complete the following steps:

`docker-compose run --rm storybook bash`
`yarn build-storybook`
`yarn loki test --chromeConcurrency 1 --requireReference --reactUri file:./storybook-static`
- Creates .png files of the current state of the stories and places them within the `.loki/current` directory. It also creates diff .png files (stored in `.loki/difference`) comparing the current .png files and the reference .png files (stored in `.loki/`). If there are any differences between the current and reference stories, the test for that story will fail. This is normal and expected. 

`yarn loki approve` <- must do this prior to committing changes
- Updates the reference images with the current images. 

Developers cannot run yarn loki test without being in docker because the dev's local environment will produce slightly different images (screenshots) than circleci's environment. This will lead to tests failing on circleci.

## For Reviewers 
I am unsure how to best document this new developer step. I would love suggestions on how to make the process clearer.

Additionally, I don't really like having to go through the 4 step process to test the new changes. Does it make sense to create a dockerfile and make file for local development? This would simplify the steps developers have to do to test.

P.S. This looks like a huge PR because it is adding all of the reference images for each component. The files are auto-generated.

## Potential Future Work

* Install `git-lfs`
* Execute `git lfs track "*.png"` (as suggested via in the loki documentation)
* Execute `git add .gitattributes` to maintain the lfs tracking

Milmove has had trouble using loki and IE11. Is this a concern for us? If so, I will need to change the storybook config file a bit. 

## References
[Loki](https://loki.js.org/getting-started.html)
[git-lfs](https://git-lfs.github.com/)

### CODE REVIEW

**Comment by trussworks-infra** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  Changes were made to yarn.lock, but no plain text yarn audit output was found in PR description. - <i>Can you run `yarn audit` in your branch and paste the results inside a markdown code block?</i>
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 385bfcc18e52b58fb73d87140a16c1d7ffaab2c5
</p>

**Comment by suzubara** [comment]
Can we include loki without requiring Docker? I know that applications like MilMove use it but since this is a library I don't want to require Docker as part of the dev environment. Also, I know we have to check in the loki reference images but do we also have to check in the static storybook files?

**Comment by eamahanna** [comment]
> Can we include loki without requiring Docker? I know that applications like MilMove use it but since this is a library I don't want to require Docker as part of the dev environment. Also, I know we have to check in the loki reference images but do we also have to check in the static storybook files?

I don't believe we can use this library without docker. I first attempted to do this, but when loki is ran locally, the images created are slightly different than those created on circleci which led to circleci failing every time. 

We don't have to check in the storybook static files. I just updated the .gitignore and removed the files.

**Comment by eamahanna** [comment]
@suzubara I just heard back from chromatic. Unfortunately the open source free plan only allows from chrome testing. It also has a snapshot limit of 35,000 per month. Given it only tests in chrome, I am not sure the collaboration tools out weight being able to in different browsers. What are your thoughts?

**Pull request closed without merging**
