### PR TITLE
build: improve DangerJS checks

### PR DESCRIPTION
**Pull request by gidjin**
# Summary

Improvements to the DangerJS checks

## How To Test

Once trussworks/react-uswds#2330 is merged you can trigger the build checks workflow to see danger execute on this branch.

### CODE REVIEW

**Comment by brandonlenz** [comment]
@gidjin anything I can verify here? I see danger has been passing on PRs, including this one. Changes look good to me as well.

**Comment by brandonlenz** [comment]
I'm also noticing that danger currently fails on main because it's looking for things that are only defined in PR context

**Comment by brandonlenz** [comment]
@all-contributors please add @gidjin for maintenance

**Comment by werdnanoslen** [comment]
@gidjin what's still needed to merge this?

**Pull request closed without merging**
