### PR TITLE
build(peer-deps): support React 18

### LINKED ISSUE #2147: [fix] Dependency issue with current react version
**ReactUSWDS Version & USWDS Version:**

**Describe the bug**

#8 2.745 npm ERR! Found: react@18.1.0
#8 2.745 npm ERR! node_modules/react
#8 2.745 npm ERR!   react@"^18.0.0" from the root project
#8 2.745 npm ERR!
#8 2.745 npm ERR! Could not resolve dependency:
#8 2.745 npm ERR! peer react@"^16.x || ^17.x" from @trussworks/react-uswds@3.0.2
#8 2.745 npm ERR! node_modules/@trussworks/react-uswds
#8 2.745 npm ERR!   @trussworks/react-uswds@"^3.0.2" from the root project

When installing the dependency, the above error was generated 

**To Reproduce**

1. install @trussworks/react-uswds on an app using react@"^18.0.0"
2. See error

**Expected behavior**

The package @trussworks/react-uswds should be installed with out error , and should not require --force, or --legacy-peer-deps

**Screenshots**

**Additional context**

**Device and Browser Information (please complete the following information if describing a UI bug):**

### PR DESCRIPTION
**Pull request by lpsinger**
Fixes #2147.

### CODE REVIEW

**Comment by lpsinger** [comment]
Ping!

**Review by codydwyertw — APPROVED** [review]
Looks like what we need

**Comment by lpsinger** [comment]
Any updates on this?

**Comment by gidjin** [comment]
I don't know why this PR isn't registering all the build jobs required. They appear to have run properly and I'm very confused as to why github doesn't see them. My only guess is it's related to the fact that this is coming from a forked repo, but that's all I can see. I opened #2197 which seems to be passing. Closing this in favor of that one.

**Pull request closed without merging**
