### PR TITLE
feat!: Uncouple uswds style

### LINKED ISSUE #2270: [fix] lib/index.css includes all USWDS styles, but should it?
**ReactUSWDS Version:** 4.1.1

**Describe the bug**

I think there's a bug, confusing documentation, or potentially both.

In the README's usage section it says:

> Also make sure to include the following in order to import the compiled CSS from this project:
> `@import '~@trussworks/react-uswds/lib/index.css';`
>If you aren't already using USWDS as a dependency, **you also need to import USWDS styles**.

In the [Styles and Assets doc](https://github.com/trussworks/react-uswds/blob/main/docs/styles_and_assets.md), it says:

> If you already have uswds as a dependency (this is most likely already the case) you only need `import '@trussworks/react-uswds/lib/index.css'` in your application.

I interpret all of the above to say:

1. Projects still need to import the `@uswds/uswds` package's CSS (or Sass)
2. `react-uswds` also has a CSS file with **additional** styles, which projects should also import.

What I'm observing however is that the `~@trussworks/react-uswds/lib/index.css` includes USWDS styles, not just additional styles.

**To Reproduce**

1. Run `yarn build` in this repo
1. Look at `lib/index.css`

**Expected behavior**

If I'm understanding correctly, I _think_ what's supposed to be happening is:

1. `index.css` includes any custom styles that are in this repo, but does not include any from the USWDS package itself
2. `uswds.css` includes the USWDS styles

**Screenshots**

Example of a USWDS style in the `index.css` file, but from what I can tell, this is only coming from USWDS:

CleanShot 2023-02-25 at 14 13 27@2x

CleanShot 2023-02-25 at 14 16 54@2x

### PR DESCRIPTION
**Pull request by jpandersen87**
# Summary

This PR removes the `@forward 'uswds'` line from the project's style index. This fixes the issue of uswds styles being included in the project's `index.css` file. Storybook's custom stylesheet has been updated to not reference the project's style index as the preview module is independently importing it along with uswds directly.

## Related Issues or PRs

closes #2270 

## How To Test

- build
- verify that index.css does not contain uswds styles

### CODE REVIEW

**Comment by sawyerh** [comment]
This seems like a nice performance quick win, thanks for doing this @jpandersen87.

**Review by kleinschmidtj — APPROVED** [review]
LGTM!

**Comment by brandonlenz** [comment]
Has this been tested on a react-uswds consuming project?

Usually that's done by updating the project dependency to the head commit of this branch:
```
"dependencies": {
  "package": "git://github.com/username/package.git#commit"
}
```

**Comment by jpandersen87** [comment]
> Has this been tested on a react-uswds consuming project?
> 
> 
> 
> Usually that's done by updating the project dependency to the head commit of this branch:
> 
> ```
> 
> "dependencies": {
> 
>   "package": "git://github.com/username/package.git#commit"
> 
> }
> 
> ```

Not directly but for our project ([ReportStream](https://github.com/CDCgov/prime-reportstream)) I've been maintaining manual patches that matches the new 'index.css' output with success. We would get unwanted side effects when attempting to use a higher version of uswds than the package used due to the discrepancies between the uswds embedded in the index at default settings and our style sheet with customized settings (at the time it was unknown that this was the cause 😫).

**Review by shkeating — APPROVED** [review]
does not appear to have design changes! good to go

**Comment by mdmower-csnw** [comment]
> Has this been tested on a react-uswds consuming project?
> 
> Usually that's done by updating the project dependency to the head commit of this branch:
> 
> ```
> "dependencies": {
>   "package": "git://github.com/username/package.git#commit"
> }
> ```

@brandonlenz 

I'm still using v5 of @trussworks/react-uswds on a project so I cherry-picked these changes on top of v5.5.0 (see [fork](https://github.com/mdmower-csnw/react-uswds/commits/5.5.0-uncouple-uswds-style/)) and tested the changes in this PR:
```
"@trussworks/react-uswds": "github:mdmower-csnw/react-uswds#5.5.0-uncouple-uswds-style",
```

The new size of `node_modules/@trussworks/react-uswds/lib/index.css` is only 3KB. The website still looks just like I expect, too.

**Review by haworku — APPROVED** [review]

**Comment by brandonlenz** [comment]
Updated title to make this a major version change, since when this merges I want this to be noted as potentially breaking due to being a large enough change. Will make life easier for consumers if they run into challenges due to a different setup

**Comment by brandonlenz** [comment]
I see this was merged! Its a good change, I never did get around to testing it on one of our projects though. 🤞🏻 my hesitation is just paranoia

**Pull request merged**
