### PR TITLE
feat: Remove example app

### PR DESCRIPTION
**Pull request by haworku**
# Summary
Remove `/example` and references to the example app. We use storybook for primary documentation and implementation examples.

## Related Issues or PRs
#2001  some discussion here of the benefits of this change

## How To Test
Library compiles and tests pass. No references to the example app remain that could confuse future contributors or maintainers.

### CODE REVIEW

**Comment by rogeruiz** [comment]
I have to fix the Danger check here. It sees that package.json was modified, but it shouldn't be reporting changes being made to the contributors section.

**Comment by rogeruiz** [comment]
@haworku i fixed the Danger check in this PR https://github.com/trussworks/react-uswds/pull/2167

**Comment by brandonlenz** [comment]
> @haworku i fixed the Danger check in this PR #2167

Just approved that one to hopefully help unblock this PR @rogeruiz

**Review by rogeruiz — APPROVED** [review]
lgtm 🌈

**Pull request merged**
