### PR TITLE
Add auto-approve workflow for dependabot

### LINKED ISSUE #98: Dependabot can't automerge PRs
Try making dependabot a code owner of yarn.lock to see if that unblocks its automerge process

### PR DESCRIPTION
**Pull request by suzubara**
Fixes #98 

Dependabot should now be able to automerge its PRs (see discussion at https://github.com/dependabot/feedback/issues/86)

### CODE REVIEW

**Comment by esacteksab** [comment]
Can we capture some documentation around the Github token that's used here? Where is it? What user does it exist under? May want to reach out to someone on Infra Reserve and grab an API token from one of our bot accounts. /cc @dynamike @eeeady

**Comment by suzubara** [comment]
@esacteksab Here's the documentation I could find about this token: https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token

**Comment by esacteksab** [comment]
> @esacteksab Here's the documentation I could find about this token: https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token

Sorry I wasn't clearer. Did you create the token as yourself? Did you create it under a different account? Want to capture where the token exists (your account or another account). If it is your account, I think someone in Infra Reserve should create the token under one of our bot accounts -- this ensures that if someone happens to your account, we have access over the token.

**Comment by suzubara** [comment]
@esacteksab I haven't created a token. The docs say Github creates it automatically, and a new one is fetched each time the action runs.

**Comment by esacteksab** [comment]
Ah! TIL. Thank you for the clarification!

**Comment by trussworks-infra** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Please add a changelog entry for your changes.</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against de4a3c86b2480535fb4ae1867953a53daa067f96
</p>

**Pull request merged**
