### PR TITLE
fix: Allow importing css from npm package

### PR DESCRIPTION
**Pull request by mdmower-csnw**
# Summary

Beginning with v8.0.0, exports from the npm package are restricted. Projects should still be able to import `lib/index.css` and `lib/uswds.css`. Add them to the [conditional exports](https://nodejs.org/api/packages.html#conditional-exports) in `package.json`. 

## Related Issues or PRs

See comment at https://github.com/trussworks/react-uswds/pull/2716#issuecomment-1982586850

## How To Test

Add `import '@trussworks/react-uswds/lib/index.css';` to any project `.ts`/`.tsx` file.

### CODE REVIEW

**Comment by mdmower-csnw** [comment]
@jpandersen87 and/or @werdnanoslen - would you mind reviewing?

**Comment by jpandersen87** [comment]
Thanks for bringing this up. I have this change alongside some other fixes for 8.0.0 here: https://github.com/trussworks/react-uswds/pull/2820

**Comment by mdmower-csnw** [comment]
> Thanks for bringing this up. I have this change alongside some other fixes for 8.0.0 here: #2820

While all your work on these fixes is very much appreciated, it's worth pointing out that combining fixes from others under your own name discourages outside contributions since there's no recorded contributions from those other people in the commit history.

**Comment by jpandersen87** [comment]
You are absolutely correct and I apologize for this error. I am still new to practices with being a contributor to outside projects vs. a codeowner. I will rebase my branch off of yours so that the git history properly attributes you as the source for the css changes, with all other changes coming from me onwards.

**Comment by jpandersen87** [comment]
This has been done. Apologies again @mdmower-csnw.

**Review by werdnanoslen — APPROVED** [review]

**Comment by werdnanoslen** [comment]
@mdmower-csnw if you can update your branch, we can merge this :)

**Pull request merged**
