### PR TITLE
feat: Add Modal deprecation warnings (non-breaking deprecation)

### LINKED ISSUE #786: [feat] Deprecate the Modal component (non-breaking)
**Does your feature request relate to a specific USWDS component?**
No

**Is your feature request related to a problem? Please describe.**
This library contains a [Modal component](https://trussworks.github.io/react-uswds/?path=/story/modal--basic) that is not part of the USWDS. It is inconsistent and outside of the scope of this library.

**Describe the solution you'd like**
Deprecate the Modal component without breaking changes by adding a console warning that will let users know the Modal component will be deprecated in the next future major release.

 **Additional context**
Instead of deleting the Modal component entirely, we should discuss moving it into a different/new Truss UI library. This will be on the agenda for future internal discussion.

### PR DESCRIPTION
**Pull request by brandonlenz**
# Summary

Adds deprecation warnings to Modal components and functions/hooks in preparation for official removal from this library

## Related Issues or PRs

closes #786 

(I'm now realizing this issue was still under "Needs Requirements". I figured it'd be some low-hanging-fruit to get a warning out to consumers of this library as early as possible. Whenever we're ready, this branch exists to be merged (or updated then merged) pending any requirement changes)

## How To Test

```
> git fetch
> git checkout bl-modal-deprecation-warning-786

> yarn storybook
```

Then preview any Modal story and take note of the console warnings (screenshots below as well)

### Screenshots (optional)

Any single export will show a deprecation warning as follows:
image

---

Multiple exports will each show specific deprecation warnings
image

---

### CODE REVIEW

**Comment by trussworks-infra** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This PR does not include changes to storybook, even though it affects component code.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>This PR does not include changes to tests, even though it affects source code.</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f4e954f6dbe1453a316054e8b5f8feb3c8f7531d
</p>

**Review by suzubara — COMMENTED** [review]
this looks great! do you mind updating the Modal tests to expect this warning? There are some examples of testing the deprecation warning in other components that use it, like `NavList`

**Comment by brandonlenz** [comment]
> this looks great! do you mind updating the Modal tests to expect this warning? There are some examples of testing the deprecation warning in other components that use it, like `NavList`

@suzubara good call. Thanks for pointing those out! d6194d3

**Review by suzubara — APPROVED** [review]
awesome, thank you!

**Comment by suzubara** [comment]
the Happo report for the last commit has some weird diffs, like icons/fonts not showing up.. it might be worth trying to re-run to see if they were spurious

**Comment by brandonlenz** [comment]
> the Happo report for the last commit has some weird diffs, like icons/fonts not showing up.. it might be worth trying to re-run to see if they were spurious

Looks like most of those went away after re-running.

That's really odd. The legitimate diffs with missing graphics appear to be in Edge. I noticed on the breadcrumb PR that the carets between breadcrumbs were rendering as squares in edge in Happo as well.

The accordion diff is weird. It looks like Happo is capturing screenshots while hovering over elements:
image

**Comment by suzubara** [comment]
yeah that is weird, I haven't seen that before. I would chalk it up to Happo since the components themselves look fine

**Pull request merged**
