### PR TITLE
build(peer-deps): add react 18 to peer deps

### PR DESCRIPTION
**Pull request by gidjin**
# Summary

To allow installation of this library in a react 18 app, modifying the peer dep requirement. Thanks @lpsinger and PR #2181

## Related Issues or PRs

Fixes https://github.com/trussworks/react-uswds/issues/2147
Closes #2181

## How To Test

Install in a react 18 app, should install no problem

### CODE REVIEW

**Comment by gidjin** [comment]
FYI here is the new PR with your change @lpsinger. CC @codydwyertw

**Review by haworku — APPROVED** [review]

**Review by haworku — APPROVED** [review]
approved! I did run this change in a react 18 app as well

**Comment by gidjin** [comment]
> approved! I did run this change in a react 18 app as well

Thank you for the approval and testing it!

**Comment by aligg** [comment]
Thanks for this fix! Ran into the React 18 error in install today and was happy to find this PR already merged after investigating further. Do we know when we'll create a new release with these changes? I was just reading these guidelines on contributing - https://github.com/trussworks/react-uswds/blob/main/docs/releasing.md If folks are amicable to it I could also try putting up a new release?

**Comment by gidjin** [comment]
> Thanks for this fix! Ran into the React 18 error in install today and was happy to find this PR already merged after investigating further. Do we know when we'll create a new release with these changes? I was just reading these guidelines on contributing - https://github.com/trussworks/react-uswds/blob/main/docs/releasing.md If folks are amicable to it I could also try putting up a new release?

I believe only npm maintainers can push the release all the way through the process. That said I plan to go through that process today.

**Comment by gidjin** [comment]
FYI Release [v3.2.0](https://github.com/trussworks/react-uswds/releases/tag/3.2.0) is out! Thanks for your patience! @aligg @lpsinger @codydwyertw

**Pull request merged**
