### PR TITLE
feat: Added required marker

### LINKED ISSUE #2523: [feat] Create required asterisk component
**Does your feature request relate to a specific USWDS component?**

All form components

**What USWDS Version is this feature present in?**

3.5.0 via https://github.com/uswds/uswds-site/pull/1834

**Is your feature request related to a problem? Please describe.**

New guidance from USWDS on showing required fields: https://designsystem.digital.gov/templates/form-templates/#identifying-required-fields-2

**Describe the solution you'd like**

1. Create an asterisk component that uses USWDS' [`<abbr>`-based element](https://designsystem.digital.gov/templates/form-templates/address-form/#component-code)
2. Import the component into the Label component and give it a boolean prop to toggle its inclusion

**Describe alternatives you've considered**

1. Simply copy-paste your own required asterisk code into every Label (still possible)
2. Create just the component and manually add the component to the Label's instance (also still possible)

**Additional context**

When using this, it's still important to put a message at the top of a form that explains what this asterisk is (e.g. "Required fields are marked with an asterisk (*)") and to use the standard `required` prop

### PR DESCRIPTION
**Pull request by werdnanoslen**
# Summary

Adds a component and storybook examples of an asterisk-based required field marker in labels

## Related Issues or PRs

Resolves #2523 

## How To Test

In storybook, see the component itself in [Form elements / Label / With Required Marker
](http://localhost:9009/?path=/story/components-form-elements-label--with-required-marker) and an example on the [address template](http://localhost:9009/?path=/story/components-form-templates--address-form)

### Screenshots (optional)
image
image

### CODE REVIEW

**Comment by werdnanoslen** [comment]
Before merging, need to update the Form stories to use this component

**Comment by werdnanoslen** [comment]
@brandonlenz in https://github.com/trussworks/react-uswds/issues/2523#issuecomment-1652281215:
> This might need to be able to be applied to a fieldset legends as well

**Comment by werdnanoslen** [comment]
@brandonlenz added to fieldset 👍

**Review by shkeating — APPROVED** [review]
looks good to me!

**Pull request merged**
