### PR TITLE
fix: Add defaultValue prop to Search component

### LINKED ISSUE #2206: [fix] Search component should support default value
**ReactUSWDS Version & USWDS Version:**

**Describe the bug**

Cannot add default value to the search component.

**To Reproduce**

1. Go to Search component story 
2. Add `defaultValue` prop and value
3. View in Storybook

**Expected behavior**

See a default value appear in the search bar 

**Screenshots**

**Additional context**

**Device and Browser Information (please complete the following information if describing a UI bug):**

### PR DESCRIPTION
**Pull request by gidjin**
PR to merge PR #2207 from @1Maria

# Summary

## Related Issues or PRs

closes #2206

### CODE REVIEW

**Comment by 1Maria** [comment]
Is it possible for me to be listed as a co-contributor on this PR?

**Comment by rogeruiz** [comment]
hey @1Maria it looks like we don't have a good email address for you to be able to give you proper attribution. Is there an email address you'd like for us to use in order to make sure that your username and icon show up in the GH interface?


The following was extracted from the `.patch` functionality of GitHub at this URL: https://github.com/trussworks/react-uswds/pull/2211.patch
```
From d8d4bc32b8b17466b21c1334ab7f67c10e2f14c0 Mon Sep 17 00:00:00 2001
From: Maria <email_address>
Date: Wed, 19 Oct 2022 22:05:49 -0400
Subject: [PATCH] Add defaultValue prop to Search component
```

**Review by brandonlenz — DISMISSED** [review]

**Comment by 1Maria** [comment]
@rogeruiz Thank you! My email is 8730830+1Maria@users.noreply.github.com

**Review by rogeruiz — APPROVED** [review]
lgtm 🌈

thanks @gidjin for giving @1Maria proper credit here.

**Comment by 1Maria** [comment]
yes, thank you!

**Pull request merged**
