### PR TITLE
feat: Deprecate the Modal component

### PR DESCRIPTION
**Pull request by brandonlenz**
> :warning: **Per #787 the modal component is to be relocated to a Truss-specific repo**: The modal component will always be available in the git history, but after merging this PR, that will be the _only_ place to find it.

# Summary

The Modal Component is no a part of `uswds` and is therefore being removed from the library.

As this is a breaking change, it is targeting the V2 release f `react-uswds`

## Related Issues or PRs

closes https://github.com/trussworks/react-uswds/issues/787

## How To Test

1. Checkout this branch
```
git fetch
git checkout bl-deprecate-modal-breaking-787
```
2. Verify all references to `Modal` are removed. 
3. Example App runs (Modal **and** redux have been removed from the example app)

### CODE REVIEW

**Comment by trussworks-infra** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>This PR does not include changes to storybook, even though it affects component code.</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>This PR does not include changes to tests, even though it affects source code.</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d15062f8d9c25d199d68c5e7fb8d80df3770d42d
</p>

**Review by haworku — APPROVED** [review]

**Comment by lpsinger** [comment]
Where will Modal live in the future? I just started using react-uswds and I am using modal.

**Comment by kalvinwang** [comment]
@lpsinger USWDS actually added a modal back to their library a year ago, so ReactUSWDS now contains a new version of the modal, as described here: https://github.com/trussworks/react-uswds/pull/1622

**Comment by lpsinger** [comment]
Oh, I see! I'm using react-uswds 2.6.0, so I guess that I am already using the new Modal component. Thanks!

**Pull request merged**
