### PR TITLE
fix: Remove image role attribute from Banner Icon component

### LINKED ISSUE #2662: [fix] HTML validation errors when using <GovBanner /> component
**ReactUSWDS Version & USWDS Version:** 6.0.0, 3.6.0

**Describe the bug**

The following errors are logged by NuHTMLValidator when using `<GovBanner />`:

```
Error: An img element which has an alt attribute whose value is the empty string must not have a role attribute.

<img class="usa-banner__icon usa-media-block__img" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj…4ODItLjgyMmgtMS42NDJ2LTEuNjQybDEyLjI5My00LjkxNXoiLz48L3N2Zz4=" role="img" alt="" aria-hidden="true">
```

```
Error: An img element which has an alt attribute whose value is the empty string must not have a role attribute.

<img class="usa-banner__icon usa-media-block__img" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj…4NFYyNy4zNEE0LjE0MiA0LjE0MiAwIDAgMCAzMiAyMy4xOTd6Ii8+PC9zdmc+" role="img" alt="" aria-hidden="true">
```

**To Reproduce**

This bug can be replicated locally or on the Trussworks storybook deployment: https://trussworks.github.io/react-uswds/iframe.html?args=&id=components-banner--gov-banner-default&viewMode=story

1. Go to Storybook's preview of `<GovBanner />`: https://trussworks.github.io/react-uswds/iframe.html?args=&id=components-banner--gov-banner-default&viewMode=story
2. Right click and inspect element on the component.
3. Right click on the page root node in the DOM HTML display, then click `Copy element`
4. Paste the source code into the HTML validator: https://validator.w3.org/nu/?showsource=yes&doc=#textarea
5. Click validate, and scroll down until you find the above errors relating to the component.

**Expected behavior**

No validation error should appear as no `role="img"` tag should be added to the graphics in the banner.

**Screenshots**

Screenshot 2023-11-16 at 15 11 06

**Device and Browser Information:**

- OS: MacOS
 - Browser: Chrome, safari, edge, etc.

### PR DESCRIPTION
**Pull request by jhancock532**
Closes #2662

### CODE REVIEW

**Review by haworku — DISMISSED** [review]
Thanks for this and linking through to related issues.

**Comment by haworku** [comment]
@jhancock532 Can you update the jest snapshot tests for  `src/components/banner/GovBanner/GovBanner.test.tsx` failures? Then I will be able to merge

**Comment by brandonlenz** [comment]
@all-contributors please add @jhancock532 for bug, code

**Comment by jhancock532** [comment]
Thanks @haworku, I've updated the snapshots

**Review by haworku — APPROVED** [review]

**Pull request merged**
